- name: Install and configure PostgreSQL
  hosts: second_server
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Install PostgreSQL and dependencies
      apt:
        name: 
          - postgresql-16
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Check if PostgreSQL user already exists
      shell: sudo -u postgres psql -c "SELECT usename FROM pg_user WHERE usename='{{ postgresql_user }}'" | grep -q '{{ postgresql_user }}'
      register: postgres_user_exists
      ignore_errors: true

    - name: Create PostgreSQL user if it doesn't exist
      shell: sudo -u postgres createuser -s "{{ postgresql_user }}"
      become: true
      when: postgres_user_exists.rc != 0

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_db_name }}"
        owner: "{{ postgresql_user }}"

    - name: Copy create_table.sh script
      copy:
        src: ../../postgresql/server_2/create_table.sh
        dest: /tmp/create_table.sh
        mode: '0755'

    - name: Check if 'categories' table exists
      shell: |
        sudo -u postgres psql -U postgres -d {{ postgresql_db_name }} -c "\dt" | grep -qw categories
      register: categories_table_exists
      failed_when: false
      changed_when: false

    - name: Check if 'tasks' table exists
      shell: |
        sudo -u postgres psql -U postgres -d {{ postgresql_db_name }} -c "\dt" | grep -qw tasks
      register: tasks_table_exists
      failed_when: false
      changed_when: false

    - name: Execute create_table.sh script
      shell: /tmp/create_table.sh
      become: true
      when: not categories_table_exists.stdout and not tasks_table_exists.stdout

    - name: Create directory for WAL archiving
      file:
        path: /archive
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Copy pg_hba.conf file to replace pg_hba.conf
      copy:
        src: ../../postgresql/server_2/pg_hba.conf
        dest: /etc/postgresql/16/main/pg_hba.conf
      notify: Reload PostgreSQL

    - name: Copy postgresql.conf file to replace postgresql.conf
      copy:
        src: ../../postgresql/server_2/postgresql.conf
        dest: /etc/postgresql/16/main/postgresql.conf
      notify: Reload PostgreSQL

  handlers:
    - name: Reload PostgreSQL
      systemd:
        name: postgresql
        state: restarted
