- name: Install and configure PostgreSQL
  hosts: third_server
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Install PostgreSQL and dependencies
      apt:
        name: 
          - postgresql-16
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Check if PostgreSQL user already exists
      shell: "sudo -u postgres psql -c \"SELECT usename FROM pg_user\" | grep -q 'replication'"
      register: postgres_user_exists
      ignore_errors: true

    - name: Create PostgreSQL user if it doesn't exist
      shell: "sudo -u postgres createuser -s replication"
      become: true
      when: postgres_user_exists.rc != 0
      ignore_errors: true

    - name: Copy postgresql.conf file to replace postgresql.conf
      copy:
        src: ../../postgresql/server_3/postgresql.conf
        dest: /etc/postgresql/16/main/postgresql.conf
      notify: Reload PostgreSQL

  handlers:
    - name: Reload PostgreSQL
      systemd:
        name: postgresql
        state: restarted
