- name: Install and configure PostgreSQL
  hosts: second_server
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Install PostgreSQL and dependencies
      apt:
        name: 
          - postgresql-16
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Configure PostgreSQL to use password authentication
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer'
        line: 'local   all             postgres                                md5'
      notify: Reload PostgreSQL

    - name: Check if PostgreSQL user already exists
      shell: sudo -u postgres psql -c "SELECT usename FROM pg_user WHERE usename='{{ postgresql_user }}'" | grep -q '{{ postgresql_user }}'
      register: postgres_user_exists
      ignore_errors: true

    - name: Create PostgreSQL user if it doesn't exist
      shell: sudo -u postgres createuser -s "{{ postgresql_user }}"
      become: true
      when: postgres_user_exists.rc != 0

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_db_name }}"
        owner: "{{ postgresql_user }}"

    - name: Copy create_table.sh script
      copy:
        src: ../postgresql/create_table.sh
        dest: /tmp/populate_db.sh
        mode: '0755'

    - name: Execute create_table.sh script
      shell: /tmp/populate_db.sh
      become: true              

    - name: Copy pg_hba.conf file
      copy:
        src: ../postgresql/pg_hba.conf
        dest: /etc/postgresql/16/main/pg_hba.conf
      notify: Reload PostgreSQL

  handlers:
    - name: Reload PostgreSQL
      systemd:
        name: postgresql
        state: restarted
